# NumPy

NumPy is the foundational library for numerical computing in Python. Think of it as Python's math powerhouse—fast, compact, and essential for data science, machine learning, simulations, and more.

In [1]:
import numpy as np


| Method / Function            | Description                            | Example                  |
| ---------------------------- | -------------------------------------- | ------------------------ |
| `np.shape()`                 | Returns dimensions of array            | `a.shape`                |
| `np.reshape()`               | Changes shape without changing data    | `a.reshape(2,3)`         |
| `np.flatten()`               | Converts multi-dimensional array to 1D | `a.flatten()`            |
| `np.transpose()`             | Swaps rows with columns                | `a.T`                    |
| `np.sum()`                   | Sum of array elements                  | `np.sum(a)`              |
| `np.mean()`                  | Mean of elements                       | `np.mean(a)`             |
| `np.std()`                   | Standard deviation                     | `np.std(a)`              |
| `np.min()`, `np.max()`       | Min or Max value                       | `np.min(a)`              |
| `np.argmin()`, `np.argmax()` | Index of Min/Max value                 | `np.argmax(a)`           |
| `np.concatenate()`           | Joins arrays                           | `np.concatenate([a, b])` |
| `np.split()`                 | Splits arrays into sub-arrays          | `np.split(a, 2)`         |


In [4]:
# 1D Array
a = np.array([1, 2, 3])
print(a)
print(type(a))
print(a.shape)

[1 2 3]
<class 'numpy.ndarray'>
(3,)


In [24]:
#Convert 1d array to 2d by using Reshape()
b=a.reshape(1,3)#but the dimensions should be clear
print(b)
print(b.ndim)

[[1 2 3]]
2


In [11]:
# 2D Array
c = np.array([[1, 2], [3, 4]])
print(type(c))
print(c)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [13]:
# Array of zeros
zeros = np.zeros((2, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
# Array of ones
ones = np.ones((3, 2))
print(ones)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [15]:
# Identity matrix
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Array with range
arange = np.arange(0, 11, 2)#syntax  np.arange(start,end,step)
print(arange)

[ 0  2  4  6  8 10]


In [22]:
# Linearly spaced array
linspace = np.linspace(0, 1, 5)
print(linspace)

[0.   0.25 0.5  0.75 1.  ]


In [ ]:
#Attributes of NumPy array
ar1=np.array([[1,2,3],[4,5,6]])
print("Array:\n",ar1)
print("ArrayShape:",ar1.shape)
print("ArrayDimensions:",ar1.ndim)
print("ArraySize:",ar1.size)
print("ArrayDataType:",ar1.dtype)
print("ItemSize(in bytes):",ar1.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
ArrayShape: (2, 3)
ArrayDimensions: 2
ArraySize: 6
ArrayDataType: int64
ItemSize(in bytes): 8


In [26]:
#Array Operations
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# Element-wise operations
add = x + y
print("Addition is:",add)
sub = x - y
print("Substraction is:",sub)
mul = x * y
print("Multiplication is:",mul)
div = x / y
print("Division is:",div)

# Dot product
dot = np.dot(x, y)
print("Dot Product is:",dot)

# Matrix multiplication
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 3]])
matmul = np.matmul(a, b)
print("Matrix Multiplication:",matmul)


Addition is: [5 7 9]
Substraction is: [-3 -3 -3]
Multiplication is: [ 4 10 18]
Division is: [0.25 0.4  0.5 ]
Dot Product is: 32
Matrix Multiplication: [[ 4  6]
 [10 12]]


In [28]:
#Universal function
ar2=np.array([2,4,5,7,8])

# square root
print(np.sqrt(ar2))

#Exponential
print(np.exp(ar2))

#sine
print(np.sin(ar2))

#natural log
print(np.log)

[1.41421356 2.         2.23606798 2.64575131 2.82842712]
[   7.3890561    54.59815003  148.4131591  1096.63315843 2980.95798704]
[ 0.90929743 -0.7568025  -0.95892427  0.6569866   0.98935825]
<ufunc 'log'>


In [ ]:
#Broadcasting Example
# Add scalar to each element
a = np.array([1, 2, 3])
a + 5  # Output: [6 7 8]

# Adding arrays of different shapes
a = np.array([[1], [2], [3]])
b = np.array([10, 20, 30])
a + b  # Broadcasts b to each row of a


array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [33]:
#Array slicing and indexing
ar3=np.array([[12,4,5,6],[1,7,8,10],[4,3,8,9]])
print(ar3.ndim)
print(ar3.shape)
print(ar3)

2
(3, 4)
[[12  4  5  6]
 [ 1  7  8 10]
 [ 4  3  8  9]]


In [35]:
print(ar3[0][3])

6


In [42]:
#Print elements in 2nd row
ar3[1:2]

array([[ 1,  7,  8, 10]])

In [48]:
#Print the elements in 4th column
print(ar3[0:,3:])

[[ 6]
 [10]
 [ 9]]


In [52]:
#for example we need to print 7 8 and 3 8
print(ar3[1:,1:3])

[[7 8]
 [3 8]]


In [53]:
#Modify an array
ar3[2,2]=20
print(ar3)

[[12  4  5  6]
 [ 1  7  8 10]
 [ 4  3 20  9]]


In [55]:
#Masking and filtering
a = np.array([1, 2, 3, 4, 5])

# Get elements > 3
mask = a > 3
filtered = a[mask]  # Output: [4 5]
print(filtered)


[4 5]


In [57]:
#Random number
np.random.seed(42)  # For reproducibility

# Random float between 0 and 1
r1 = np.random.rand()
print(r1)

# Random array
r2 = np.random.rand(2, 3)
print(r2)

# Random integers
r3 = np.random.randint(1, 10, size=(2, 2))
print(r3)


0.3745401188473625
[[0.95071431 0.73199394 0.59865848]
 [0.15601864 0.15599452 0.05808361]]
[[8 5]
 [4 8]]


In [58]:
#statistical concepts : Normalization
#To have a mean pf 0 and standard deviation of 1
data=np.array([1,2,3,4,5,6])

#Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)
#Normalize the data
normalized_data=(data-mean)/std_dev
print("Normalized data:",normalized_data)


Normalized data: [-1.46385011 -0.87831007 -0.29277002  0.29277002  0.87831007  1.46385011]


In [59]:
data=np.array([2,3,4,5,6,8,9,10,12])

#Mean
mean=np.mean(data)
print(mean)

#Median
median=np.median(data)
print(median)

#standard deviation
std_dev=np.std(data)
print(std_dev)

#Varience
varience=np.var(data)
print(varience)


6.555555555555555
6.0
3.201080064641763
10.246913580246915


In [63]:
#Logical Operation
data=np.array([4,5,3,7,8,12,24,18])
print(data[(data>10) & (data<=30)])


[12 24 18]


Conclusions : NumPy arrays are faster and more memory-efficient than Python lists. Use NumPy for any numerical computation involving vectors, matrices, or large datasets.